# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lucio}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Plinio Balduino", "Rodrigo Lorca"]
  s.date = %q{2011-07-08}
  s.default_executable = %q{lucio}
  s.description = %q{Lucio is intended to be a Lisp-like language developed in Ruby only for knowledge and fun.}
  s.email = %q{pbalduino+github@gmail.com}
  s.executables = ["lucio"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lucio.gemspec",
    "lib/lucio.rb",
    "lib/lucio_syntax.treetop",
    "lib/lucio/grammar.rb",
    "lib/lucio/lexicon.rb",
    "lib/lucio/lucio.rb",
    "lib/lucio/operators.rb",
    "lib/lucio/runner.rb",
    "lib/lucio/operators/division.rb",
    "lib/lucio/operators/equality.rb",
    "lib/lucio/operators/function.rb",
    "lib/lucio/operators/multiplication.rb",
    "lib/lucio/operators/subtraction.rb",
    "lib/lucio/operators/sum.rb",
    "bin/repl.rb",
    "bin/lucio.bat"
  ]
  s.homepage = %q{https://github.com/pbalduino/lucio}
  s.licenses = ["MIT"]
  s.require_paths = ["bin", "lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Lucio is a LISP-like language}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
  end
end
