# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lucio}
  s.version = "0.0.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["pbalduino"]
  s.date = %q{2011-07-19}
  s.description = %q{Lucio is intended to be a Lisp-like language developed in Ruby only for knowledge and fun.}
  s.email = %q{pbalduino+github@gmail.com}
  s.executables = ["lucio", "repl.rb"]
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/lucio",
    "bin/repl.rb",
    "lib/lucio.rb",
    "lib/lucio/lexicon.rb",
    "lib/lucio/lucio.rb",
    "lucio.gemspec",
    "spec/add_spec.rb",
    "spec/behead_spec.rb",
    "spec/divide_spec.rb",
    "spec/empty_list_spec.rb",
    "spec/internal_spec.rb",
    "spec/let_spec.rb",
    "spec/minus_spec.rb",
    "spec/readme_examples_spec.rb",
    "spec/spec_helper.rb",
    "spec/times_spec.rb"
  ]
  s.homepage = %q{https://github.com/pbalduino/lucio}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Lucio is a LISP-like language created just for fun}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sparse>, ["~> 0.0.3"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.4.0"])
    else
      s.add_dependency(%q<sparse>, ["~> 0.0.3"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<simplecov>, ["~> 0.4.0"])
    end
  else
    s.add_dependency(%q<sparse>, ["~> 0.0.3"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<simplecov>, ["~> 0.4.0"])
  end
end

