# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lucio}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["pbalduino"]
  s.date = %q{2011-07-14}
  s.description = %q{Lucio is intended to be a Lisp-like language developed in Ruby only for knowledge and fun.}
  s.email = %q{pbalduino+github@gmail.com}
  s.executables = ["lucio"]
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".autotest",
    ".document",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "TODO.md",
    "VERSION",
    "bin/lucio",
    "bin/repl.rb",
    "lib/lucio.rb",
    "lib/lucio/grammar.rb",
    "lib/lucio/lexicon.rb",
    "lib/lucio/lucio.rb",
    "lib/lucio/operators.rb",
    "lib/lucio/operators/conditional.rb",
    "lib/lucio/operators/division.rb",
    "lib/lucio/operators/equality.rb",
    "lib/lucio/operators/function.rb",
    "lib/lucio/operators/macro.rb",
    "lib/lucio/operators/multiplication.rb",
    "lib/lucio/operators/subtraction.rb",
    "lib/lucio/operators/sum.rb",
    "lib/lucio/runner.rb",
    "lib/lucio_syntax.treetop",
    "lucio.gemspec",
    "spec/eval_spec.rb",
    "spec/lucio_spec.rb",
    "spec/parser_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{https://github.com/pbalduino/lucio}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Lucio is a LISP-like language created just for fun}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<polyglot>, [">= 0"])
      s.add_runtime_dependency(%q<treetop>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<ZenTest>, [">= 0"])
      s.add_development_dependency(%q<diff-lcs>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<polyglot>, [">= 0"])
      s.add_dependency(%q<treetop>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<ZenTest>, [">= 0"])
      s.add_dependency(%q<diff-lcs>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<polyglot>, [">= 0"])
    s.add_dependency(%q<treetop>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<ZenTest>, [">= 0"])
    s.add_dependency(%q<diff-lcs>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

